spring:     
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${{ secrets.DB_PASSWORD }}
    username: postgres
    url: jdbc:postgresql://kindercloud.ddns.net:5432/solaris
    hikari:
      schema: solaris
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        default-schema: solaris
