spring:     
  datasource:
    driverClassName: org.postgresql.Driver
    password: aritzdp
    username: postgres
    url: jdbc:postgresql://localhost:5432/solaris
    hikari:
      schema: solaris

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        default-schema: 

  thyemeleaf:
    cache: false
  
