spring:     
  datasource:
    driverClassName: org.postgresql.Driver
    password:
    username: postgres
    url: jdbc:postgresql://localhost:5432/solaris
    hikari:
      schema: solaris
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        default-schema: solaris
  flyway:
    location: classpath:/db/migration