spring:     
  datasource:
    driverClassName: org.postgresql.Driver
    password: 
    username: postgres
    url: jdbc:postgresql://kindercloud.ddns.net:5432/solaris?schema=solaris
    hikari:
      schema: solaris
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        default-schema: solaris

  security:
    user:
      name: admin
      password: admin

logging:
    level:
      org:
        hibernate:
          #type: TRACE
          #SQL: TRACE


