/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 21 09:39:47 GMT 2022
 */

package eus.solaris.solaris.dto;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import eus.solaris.solaris.service.multithreading.conversions.ConversionType;
import eus.solaris.solaris.service.multithreading.modes.GroupMode;

public class SolarPanelRequestDTOTest {

    @Test
    @Timeout(4)
    public void test00() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        LocalDate localDate0 = LocalDate.ofYearDay(4, 4);
        solarPanelRequestDTO0.setStart(localDate0);
        LocalDate localDate1 = solarPanelRequestDTO0.getStart();
        assertSame(localDate1, localDate0);
    }

    @Test
    @Timeout(4)
    public void test01() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        Long long0 = 2423L;
        solarPanelRequestDTO0.setId(long0);
        Long long1 = solarPanelRequestDTO0.getId();
        assertEquals(2423L, (long) long1);
    }

    @Test
    @Timeout(4)
    public void test02() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        Long long0 = -501L;
        solarPanelRequestDTO0.setId(long0);
        Long long1 = solarPanelRequestDTO0.getId();
        assertEquals((-501L), (long) long1);
    }

    @Test
    @Timeout(4)
    public void test03() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        LocalDate localDate0 = LocalDate.ofYearDay(4, 4);
        solarPanelRequestDTO0.setEnd(localDate0);
        LocalDate localDate1 = solarPanelRequestDTO0.getEnd();
        assertSame(localDate1, localDate0);
    }

    @Test
    @Timeout(4)
    public void test04() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        ConversionType conversionType0 = ConversionType.TO_AVOIDED_CO2;
        solarPanelRequestDTO0.setConversionType(conversionType0);
        ConversionType conversionType1 = solarPanelRequestDTO0.getConversionType();
        assertEquals(ConversionType.TO_AVOIDED_CO2, conversionType1);
    }

    @Test
    @Timeout(4)
    public void test05() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        solarPanelRequestDTO0.getConversionType();
    }

    @Test
    @Timeout(4)
    public void test06() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        Long long0 = solarPanelRequestDTO0.getId();
        assertNull(long0);
    }

    @Test
    @Timeout(4)
    public void test07() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        LocalDate localDate0 = solarPanelRequestDTO0.getStart();
        assertNull(localDate0);
    }

    @Test
    @Timeout(4)
    public void test08() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        solarPanelRequestDTO0.getGroupMode();
    }

    @Test
    @Timeout(4)
    public void test09() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        LocalDate localDate0 = solarPanelRequestDTO0.getEnd();
        assertNull(localDate0);
    }

    @Test
    @Timeout(4)
    public void test10() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        GroupMode groupMode0 = GroupMode.DAY;
        solarPanelRequestDTO0.setGroupMode(groupMode0);
        GroupMode groupMode1 = solarPanelRequestDTO0.getGroupMode();
        assertEquals(GroupMode.DAY, groupMode1);
    }

    @Test
    @Timeout(4)
    public void test11() throws Throwable {
        SolarPanelRequestDTO solarPanelRequestDTO0 = new SolarPanelRequestDTO();
        Long long0 = 0L;
        solarPanelRequestDTO0.setId(long0);
        Long long1 = solarPanelRequestDTO0.getId();
        assertEquals(0L, (long) long1);
    }
}
