/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 21 11:27:27 GMT 2022
 */

package eus.solaris.solaris.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import eus.solaris.solaris.domain.Comunidad;
import eus.solaris.solaris.domain.Provincia;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Provincia_ESTest extends Provincia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Integer integer0 = Integer.getInteger("%kn1)x56Dt|.(", 0);
      provincia0.setId(integer0);
      Integer integer1 = provincia0.getId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Integer integer0 = new Integer(1);
      provincia0.setId(integer0);
      Integer integer1 = provincia0.getId();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Integer integer0 = new Integer((-1846));
      provincia0.setId(integer0);
      Integer integer1 = provincia0.getId();
      assertEquals((-1846), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      provincia0.setCapitalProvincia("");
      String string0 = provincia0.getCapitalProvincia();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Comunidad comunidad0 = new Comunidad();
      provincia0.setComunidad(comunidad0);
      Comunidad comunidad1 = provincia0.getComunidad();
      assertNull(comunidad1.getComunity());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Integer integer0 = provincia0.getId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      provincia0.setCapitalProvincia("%kn1)x56Dt|.(");
      String string0 = provincia0.getCapitalProvincia();
      assertEquals("%kn1)x56Dt|.(", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      String string0 = provincia0.getCapitalProvincia();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Provincia provincia0 = new Provincia();
      Comunidad comunidad0 = provincia0.getComunidad();
      assertNull(comunidad0);
  }
}
