/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 25 13:50:17 GMT 2022
 */

package eus.solaris.solaris.domain;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

class BrandTest {

  @Test
  @Timeout(4)
  void test00() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("N3M~Thbu *R&KD");
    String string0 = brand0.getName();
    assertEquals("N3M~Thbu *R&KD", string0);
  }

  @Test
  @Timeout(4)
  void test01() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("");
    String string0 = brand0.getName();
    assertEquals("", string0);
  }

  @Test
  @Timeout(4)
  void test02() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = (0L);
    brand0.setId(long0);
    Long long1 = brand0.getId();
    assertEquals(0L, (long) long1);
  }

  @Test
  @Timeout(4)
  void test03() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = (2112L);
    brand0.setId(long0);
    Long long1 = brand0.getId();
    assertEquals(2112L, (long) long1);
  }

  @Test
  @Timeout(4)
  void test04() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = ((-1126L));
    brand0.setId(long0);
    Long long1 = brand0.getId();
    assertEquals((-1126L), (long) long1);
  }

  @Test
  @Timeout(4)
  void test05() throws Throwable {
    Brand brand0 = new Brand();
    boolean boolean0 = brand0.canEqual(brand0);
    assertTrue(boolean0);
  }

  @Test
  @Timeout(4)
  void test06() throws Throwable {
    Brand brand0 = new Brand();
    boolean boolean0 = brand0.canEqual((Object) null);
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test07() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = brand0.getId();
    assertNull(long0);
  }

  @Test
  @Timeout(4)
  void test08() throws Throwable {
    Brand brand0 = new Brand();
    String string0 = brand0.getName();
    assertNull(string0);
  }

  @Test
  @Timeout(4)
  void test09() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("");
    Brand brand1 = new Brand();
    assertFalse(brand1.equals((Object) brand0));

    brand1.setName("");
    boolean boolean0 = brand1.equals(brand0);
    assertTrue(brand1.equals((Object) brand0));
    assertTrue(boolean0);
  }

  @Test
  @Timeout(4)
  void test10() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("");
    Brand brand1 = new Brand();
    boolean boolean0 = brand1.equals(brand0);
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test11() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("P}7");
    Brand brand1 = new Brand();
    boolean boolean0 = brand0.equals(brand1);
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test12() throws Throwable {
    Brand brand0 = new Brand();
    Brand brand1 = new Brand();
    assertTrue(brand1.equals((Object) brand0));

    Long long0 = ((-2422L));
    brand1.setId(long0);
    boolean boolean0 = brand0.equals(brand1);
    assertFalse(brand1.equals((Object) brand0));
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test13() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = (0L);
    Brand brand1 = new Brand();
    assertTrue(brand1.equals((Object) brand0));

    brand1.setId(long0);
    boolean boolean0 = brand1.equals(brand0);
    assertFalse(brand1.equals((Object) brand0));
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test14() throws Throwable {
    Brand brand0 = new Brand();
    Object object0 = new Object();
    boolean boolean0 = brand0.equals(object0);
    assertFalse(boolean0);
  }

  @Test
  @Timeout(4)
  void test15() throws Throwable {
    Brand brand0 = new Brand();
    boolean boolean0 = brand0.equals(brand0);
    assertTrue(boolean0);
  }

  @Test
  @Timeout(4)
  void test16() throws Throwable {
    Brand brand0 = new Brand();
    brand0.setName("");
    brand0.hashCode();
  }

  @Test
  @Timeout(4)
  void test17() throws Throwable {
    Brand brand0 = new Brand();
    brand0.hashCode();
  }

  @Test
  @Timeout(4)
  void test18() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = ((-1L));
    brand0.setId(long0);
    brand0.hashCode();
  }

  @Test
  @Timeout(4)
  void test19() throws Throwable {
    Brand brand0 = new Brand();
    String string0 = brand0.toString();
    assertEquals("Brand(id=null, name=null)", string0);
  }

  @Test
  @Timeout(4)
  void test20() throws Throwable {
    Brand brand0 = new Brand();
    Long long0 = (0L);
    brand0.setId(long0);
    Brand brand1 = new Brand();
    assertFalse(brand1.equals((Object) brand0));

    brand1.setId(long0);
    boolean boolean0 = brand1.equals(brand0);
    assertTrue(brand1.equals((Object) brand0));
    assertTrue(boolean0);
  }
}
