/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 21 11:27:27 GMT 2022
 */

package eus.solaris.solaris.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

class ProvinciaTest {

    @Test
    @Timeout(4)
    void test0() throws Throwable {
        Provincia provincia0 = new Provincia();
        Integer integer0 = Integer.getInteger("%kn1)x56Dt|.(", 0);
        provincia0.setId(integer0);
        Integer integer1 = provincia0.getId();
        assertEquals(0, (int) integer1);
    }

    @Test
    @Timeout(4)
    void test1() throws Throwable {
        Provincia provincia0 = new Provincia();
        Integer integer0 = 1;
        provincia0.setId(integer0);
        Integer integer1 = provincia0.getId();
        assertEquals(1, (int) integer1);
    }

    @Test
    @Timeout(4)
    void test2() throws Throwable {
        Provincia provincia0 = new Provincia();
        Integer integer0 = -1846;
        provincia0.setId(integer0);
        Integer integer1 = provincia0.getId();
        assertEquals((-1846), (int) integer1);
    }

    @Test
    @Timeout(4)
    void test3() throws Throwable {
        Provincia provincia0 = new Provincia();
        provincia0.setCapitalProvincia("");
        String string0 = provincia0.getCapitalProvincia();
        assertEquals("", string0);
    }

    @Test
    @Timeout(4)
    void test4() throws Throwable {
        Provincia provincia0 = new Provincia();
        Comunidad comunidad0 = new Comunidad();
        provincia0.setComunidad(comunidad0);
        Comunidad comunidad1 = provincia0.getComunidad();
        assertNull(comunidad1.getComunity());
    }

    @Test
    @Timeout(4)
    void test5() throws Throwable {
        Provincia provincia0 = new Provincia();
        Integer integer0 = provincia0.getId();
        assertNull(integer0);
    }

    @Test
    @Timeout(4)
    void test6() throws Throwable {
        Provincia provincia0 = new Provincia();
        provincia0.setCapitalProvincia("%kn1)x56Dt|.(");
        String string0 = provincia0.getCapitalProvincia();
        assertEquals("%kn1)x56Dt|.(", string0);
    }

    @Test
    @Timeout(4)
    void test7() throws Throwable {
        Provincia provincia0 = new Provincia();
        String string0 = provincia0.getCapitalProvincia();
        assertNull(string0);
    }

    @Test
    @Timeout(4)
    void test8() throws Throwable {
        Provincia provincia0 = new Provincia();
        Comunidad comunidad0 = provincia0.getComunidad();
        assertNull(comunidad0);
    }
}
