/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 21 11:31:46 GMT 2022
 */

package eus.solaris.solaris.service.impl;

import static org.junit.Assert.assertThrows;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import eus.solaris.solaris.domain.User;

class SolarPanelServiceImplTest {

  @Test
  @Timeout(4)
  void test0() throws Throwable {
    SolarPanelServiceImpl solarPanelServiceImpl0 = new SolarPanelServiceImpl();
    User user0 = new User();
    assertThrows(NullPointerException.class, () -> solarPanelServiceImpl0.findByUser(user0));
  }
}
